server:
  servlet:
    session:
      timeout: 20s

spring:
  datasource:
    url: jdbc:mysql://116.62.148.11:3306/xxx?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
  resources:
    static-locations: classpath:public,classpath:templates
  security:
    loginType: json